### ISSUE TITLE
First Organizational Meeting - March 12th 6 pm

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseq18#1]
It's time to start organizing hackseq18!

We'll hold the first meeting, the week of 6pm on the March 12-16th (please fill out the poll below). The objective of the meeting will be to organize ourselves into a working group, divide tasks and establish a timeline of when/what needs to be accomplished.

Previous organizers (@hackseq/steering_committee_2016 @jasgrewal @jakelever... more?) will be present and help guide the process and provide mentorship to the incoming organizational committee!

Please get in touch with motivated and competent individuals and refer them to this issue if they would like to show up. Everyone is welcome to help out as much or as little as they would like, but we'll likely settle into ~8-12 person group as being solely responsible for an aspect of the event.

### [Poll Link](https://dudle.inf.tu-dresden.de/hs18/)

(Assign someone to take meeting minutes)

## Agenda Items (feel free to add)
- Hello + Welcome

### hackseq17
- Summary from previous committee
- Budget and finances

### hackseq18
- New organizing committee
- - Positions
- - Additional Recruitment

- Logistics
- - Event Date / Format
- - Location Choice
- - Organizational Time-table
- - Projected Budget

- Website (Artem)
- - update frontpage
- - hackseq18 registration / splash page
- - hackseq17 summary / teaser page (hs17?)

- Partnerships
- - ECOSCOPE (email sent)
- - Medical Genetics
- - GrassPods
- - SCWIST

- Tasks for Second Organizational Meeting

**Comment by sjackman** [comment]
I have a particularly full week that week. I could possibly make Tue or Thu night, but don't schedule around me.

**Comment by ababaian** [comment]
# Action Items
- [ ] Send out recruitment email to hackseq mailing list asking for people interested helping in organization. Ideally ~10 total. ( Jen )
- [ ] Send out email to the previous team leaders and ask for an update on the project if there are any. We can use this for sponsorship/team lead recruitment going forward ( ? )
- [x] Start Private Repo for hackseq 18, add organizers as admins ( Artem )
- [ ] Initialize website for hackseq18 ( Artem )
- [ ] Create summary page for hackseq17 (i.e. hs16 page) ( Jake --> Jasleen? )
- [x] Schedule next meeting w/ more organizers in 2 weeks time ( ? )

# Minutes
In attendance: Lauren, Jake, Artem, Emrhan, Alex, Baraa

### hackseq17
Summary from previous committee

Major Issues
-- One food vendor had a hick-up, wasn't confirmed, ended up switching food on day 1
-- Matching skills to the project (some projects are R required / desired )

Manuscript Writing
- Groups were engaged in writing quite well. Few manuscripts are pending!

Virtual Participants:
-- Decide if you want to allow, +/- with it (mostly beneficial)
-- Entirely virtual team (idea)
-- Remote Teams --> if Team Leader can organize it, make it happen. (idea)

Barrier to Entry
-- Virtual participation not showing up on Day 1 was quite high (1/2)
-- Virtual Mixer (pre-week) (idea)
-- Fee: $5 - $10 (idea)
-- Increasing barrier to entry / focus on highly motivated individuals
-- Also meant food leftovers

Team Leaders Recruitment
-- Most important part for everyone to be involved!
-- Recruit, recruit, recruit! (blackmail your friends)
-- Advice team leaders to send out pre-event information and primers

- Budget and finances
-- On hackseq google drive

### hackseq18

Budget
-- SCWIST took care of finances (again?)
-- Make childcare options available again

Sponsorship
-- Start emailing soon
-- Companies may request an invoice
-- Play up educational / open science options

New organizing committee
- - Additional Recruitment
- - 5 + Jennifer, Emre has +1
- - Jasleen can probably do location-oriented tasks if we ask nice


Application Notes
[ Get github ID and food allergy info right away ]
[ Confirmation emails ]
[ Conferences tack on to near/around October ]

Organizational Time-table
-- Team Leader App Open   (mid-late April)
-- Team Leader App Close  (Mid July)
-- Team Leader Selection  (End of July)

-- Participant App Open   (August)
-- Participant App Close  (September)
-- Participant Assignment (September)

-- Event Date / Format
-- Start Friday vs. Saturday

Location (need to be choosen as soon we have date)
-- Food / 
-- Security

- Website (Artem)
-- update frontpage
-- hackseq18 registration / splash page
-- hackseq17 summary / teaser page (hs17?)

- Social Media ()

- Partnerships
-- ECOSCOPE (email sent)
-- Medical Genetics
-- GrassPods
-- SCWIST
-- Amazon Credits (issue on hs17_private repo)
-- ORCA (Scott Baker / S. Jackman to liase)

**Comment by jenjaelin** [comment]
I'd be happy to take on either of the email tasks. Is there any sort of template or reference I can follow off of?

J

**Comment by emreerhan** [comment]
I talked to @sjackman , he said he would be willing to lead a team and help out with setting up Orca. Although he wants to avoid being the go-to tech support guy.

**Comment by ababaian** [comment]
@jenjaelin Great, can you do the organizational email? I can get you hooked up with the hackseq email account.

Maybe once you draft it up, open an issue and post it there and we can figure out what else would have to go into it.

**Comment by jenjaelin** [comment]
yep sounds good! basically a "hey, we're looking for people interested in organizing hackseq -insert blurb about what we are-" ?

**Comment by ababaian** [comment]
The email will go out the hackseq mailing list so you can assume people know who we are and the majority of those people will have participated in a hackseq event previously. I think it's just about getting people excited about it (i.e. why would they enjoy helping organize a hackathon?)

**Comment by ababaian** [comment]
Hey @jasgrewal,

One of the rumours that came up during the meeting is that you'd be willing to help out with organizing the location (assuming it's LSI again). If this is true I'll add you to the organizing committee and we'll only bother you with business directly concerning the location?

**Comment by jenjaelin** [comment]
cool cool I'll have a draft ready in the next few days.

**Comment by baraaorabi** [comment]
Update: I got in touch with couple of my friends from my bioinformatics cohort: Sasha and Kristen. Sasha participated in Hackseq17 and Kristen is an organizer of SFU OMICS group.

I will also talk to some of the other OMICS organizers tomorrow after a workshop they are holding at SFU.

Sasha has a concern (which I also share) about whether we as organizers can still participate in Hackseq18. What do you guys think?

**Comment by sjackman** [comment]
I was a team leader and organized Hackseq16, so it's possible to do both. You'll definitely need some organizers who are not participating, to focus on day-of logistics.

**Comment by klgray25** [comment]
Hi everyone! I heard that you are still looking for organizers for Hackseq 2018 and I would love to help out! Please let me know if there are still positions to fill and what I can do to get involved.
Best,
Kristen

**Comment by ababaian** [comment]
Let's get the organizers to meet next week. @emreerhan  / @baraaorabi  can one of you organize? I'm in a bit of a time crunch until the 30th. Once we get a time I can get us a room at the BCCRC.

**Comment by emreerhan** [comment]
@ababaian I made a new issue. I haven't added agenda items, but I'll do so as I think of them. Feel free to add any.
