### ISSUE TITLE
[ Off Topic ] - bioSyntax Survey

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseq18#10]
Hey gang,

Can I ask a small favor. Can you take ~5 minutes to complete [this questionnaire](https://goo.gl/forms/YO89fEPw71JpH3Ac2) about bioinformatics work-space. We had some questions for bioSyntax from a reviewer and we'd like to gather a little bit of data for future development and to to see if our assumptions hold true.

Also if you can email / share the link with anyone who is in computational biology or related work we'd really appreciate it!

Artem / bioSyntax Devs

Link: https://goo.gl/forms/YO89fEPw71JpH3Ac2

**Comment by emreerhan** [comment]
Done!
