### ISSUE TITLE
6th Organizational Meeting - Thursday July 5th at 6PM *Minutes posted

### ISSUE THREAD

**Issue by jenjaelin** [hackseq/hackseq18#16]
# To Do's before meeting

- [x] - vote for a meeting time [here](https://doodle.com/poll/dwmkufxzfzyzmifm) (if you cannot attend period, please click the "cannot attend" button in the bottom right)
     - see you at BCCRC at **6pm on Thursday**!

- [x] - sign up for 1 or more interview slots [here](https://docs.google.com/spreadsheets/d/1Ufwg3ZZ5KMtk9Go5BWHPxGLgydqXvr31Ql3WxXZJY9Q)

- [x] - contribute to potential interview questions for applicants [here](https://docs.google.com/document/d/1WzP-s2bGyHGlH0ySC9IddW9mwEo0opctEt6C62PG4rY/edit?usp=sharing) **before July 3rd**

# Minutes
## TL applications/interviews
- new leaders
    - NIH - send her a more detailed application since she cannot send in application 
    - Abcellura - wants to run a team for being a sponsor - **Justin** will talk to them
    - One other possible application to come from Ecoscope - **Emre** will remind on Monday
    -  3 other new applications
- total 8+2(3?) total applications

- breakdown of the skills are broken down well in the bio
    -   collect the information during interview
    -   for skills - ask what specific things the TLs wanted (milestones)
    -  abstract of 250 words, specific skills and ratings, biology skills (mandatory skills for everyone + domain specific knowledge)  - have "OR" lists for prerequisites
    -  ask the team leaders to provide readings/tutorial information ~ 1 month beforehand
        -  have templates available for it

## Participant Recruitment
-  Kristen will start prep a google form
-  skill list preparation - wait for interviews to come back
-  start applications at mid August (as early as possible)
-  send ad slide to profs to ask to help recruit

## Logistics
- **Sasha** - tentative schedule for what is going on where and when
- have git workshop ~30 min around 10:30
- **Emre** - to ask Shawn/Jake about the paperwork for wifi

## Funding and Sponsorships
- lots of in kind donations (computing credit, swag)
- **Jenny** to write out app for BCCHR
- give extra credits to participants/TL
- UBC excellence fund - **Justin** will look into it
- GrasPods - want written letter from us saying what the money will be used if HackSeq doesn't move forward. Artem/Jasleen will go to meeting Friday to sort out.
- Consider incorporating/having a bank account/starting coop would work 

## Misc
- writer workshops - 10 min meeting each day (Instruction, keeping track to tasks, wrap up)
- 350 word abstract for each project on what was accomplished as a deliverable
- git workshop - find someone to run - **Emre** to ask Bruno
- what is the goal for a project? - encourage publication
- Change credit card to **Artem**

## Action items for next meeting 
- By tomorrow - sign up for interview (2 per organizer)
- Next meeting - either week of 23rd or 30th.
- discuss frequency of meetings
- post itemized list of action items - **Jenny**
- look into Google Colab

**Comment by baraaorabi** [comment]
So are we settling for Thu 6pm for the meeting?

**Comment by jenjaelin** [comment]
Yeah sure! I was gonna update this when I got home tn

J

**Comment by ababaian** [comment]
Just to confirm this is tonight, on Thursday correct (the 5th)? See you all there!

**Comment by jenjaelin** [comment]
yessir. See everyone at 6PM around the lobby :)

**Comment by jenjaelin** [comment]
ah oops, my bad with the date

**Comment by NoushinN** [comment]
Looks like this has to go without me! :( Please count me in for interviews through skype and a mock interview (3 hours difference/Toronto time!) :)
I really wanted to bring up the topic of what we can do as organizers to help and set expectations for team leaders, and of course hear your opinions for how we can unify team leader's output and notify them of our expectations, e.g. guidelines for desired outcomes, etc. be it in the form of a generic github templates for each project, or others 
Also thoughts on whether we should communicate this hackathon in an f1000 publication?

**Comment by vlauu** [comment]
Hey everyone, I won't be able to attend today's meeting as well, but below is my update regarding sponsorships:

So far, @imasianxd  and I secured monetary sponsorships from RStudio ($500USD) and bioinformatics.ca ($500), both pending for an invoice and wire instructions, which leads a potential problem that might want to be discussed today:

Colin Hammond, treasurer of GrasPods, mentioned that it's not 100% confirmed that GrasPods can issue invoices and reimbursements for us - should be able to give us a confirmation by early next week. If this does not work out, what would be our alternative? SCWIST?
