### ISSUE TITLE
hackseq schedule

### ISSUE THREAD

**Issue by bfjia** [hackseq/hackseq18#17]
One of the sponsor requested a rough schedule for the days. since we don't have one for this year, can someone hook me up with last year's schedule? thx

**Comment by ababaian** [comment]
Not sure about 2017 but the [2016 Schedule can be found here.](https://github.com/hackseq/October_2016/blob/master/schedule.pdf)

It's very likely to be the same but maybe we can get the logistics leads to start drafting one.

**Comment by ababaian** [comment]
@smaslova when you get a chance there's an email for you regarding the room booking on the hackseq account.

**Comment by NoushinN** [comment]
irrelevant post @smaslova but can you send me your email? I am trying to email you and Morgan Bye to set up time for interview, thanks

**Comment by emreerhan** [comment]
@smaslova so to confirm, Bruno is requesting a total 1.5 hour time slot on the first day of the hackathon for the optional GitHub workshop. The first 45 mins is for his full session, and the next 45 mins is to reinforce concepts to accommodate people with no version control experience.

**Comment by emreerhan** [comment]
@smaslova so to confirm, Bruno is requesting a total 1.5 hour time slot on the first day of the hackathon for the optional GitHub workshop. The first 45 mins is for his full session, and the next 45 mins is to reinforce concepts to accommodate people with no version control experience.

**Comment by NoushinN** [comment]
@imasianxd just came across github hackathon sponsorship, i.e. we could fill this form and if fit, they could sponsor our hackseq, check it out https://community.github.com/

**Comment by ababaian** [comment]
Do I have a schedule outline which I can put online?

**Comment by smaslova** [comment]
There's a schedule on the hackseq18 private repo that's up to date with
what we have so far.  I haven't heard back yet regarding classroom bookings.
