### ISSUE TITLE
7th Organizational Meeting - Monday, July 30th @6pm *Minutes posted

### ISSUE THREAD

**Issue by jenjaelin** [hackseq/hackseq18#18]
# To Dos:
## Everyone
- [x] vote for **2** meeting times (one per week) [here](https://doodle.com/poll/i5bc5uvgixktudbr) (if you cannot attend period, please click the "cannot attend" button in the bottom right) - Complete by **July 13th**
- [x] start arranging interviews with your assigned TL(s) (after email template is finalized)
- [x] sign up for 2  interview slots [here](https://docs.google.com/spreadsheets/d/1Ufwg3ZZ5KMtk9Go5BWHPxGLgydqXvr31Ql3WxXZJY9Q) by **July 7th**

## Individual
Please check them off as they are completed
### Artem
- [x] Change credit card
- [x] Meeting with GrassPods on Friday
### Emre
- [x] Remind Ecoscope TL for application on **July 9th**
- [x] Write an email template to send out to TLs regarding interviews
- [x] Shawn/Jake about the paperwork for wifi
- [x] ask Bruno about running git workshop
### Jenny
- [ ] BCCHR application
- [x] clean up questions and send simplified list to **Emre** by July 9th for TLs
### Justin
- [x] To talk to Abcellera about running a team
- [x] inquire about UBC excellence fund
### Kristen
- [x] start prepping a google form for Participant recruitment
### Sasha
- [x]  tentative schedule for the weekend of

# Agenda Items
## Misc
- discuss frequency of meetings from hereon in 

# Minutes

## Team lead updates
* 8 confirmed team leaders
* Alex Sweeten
* Rob Gilmore
* Noushin Nabavi
* Sam Chorlton
* Morgan Bye/Cara Reisle
* Shaun Jackman, Rayan Chikhi, 
* Veena Ghorakavi
* Arjun Baghela

Still awaiting a response from Allissa Dillman from the NIH.

@baraaorabi is going to talk to Dr. Faraz Hach about leading a team too.

Rob Gilmore is requesting travel funding. The discussion is [here](https://github.com/hackseq/hackseq18_private/issues/13).

## To do

- [ ] Confirm LSC booking @smaslova 
- [ ] @SweetiePi will email old team leaders to ask if they are willing to talk to current team leaders about leading teams.
- [ ] @emreerhan will email UBC IT about wifi.
- [ ] interviewers will send @klgray25 2 sentence summaries of projects.
- [x] @NoushinN start a facebook page for hackseq; it's a social media platform we're currently lacking. @baraaorabi offered to assist.
- [ ] Create issue about hackseq draft schedule so we can all discuss/comment @smaslova 
- [ ] Update Budget for 2018 @vlauu 
- [ ] Contact Team Leads and for Promotional Materials from them #19 / #20 @emreerhan 
- [x] Ask Faraz Hach to potentially lead a team @baraaorabi
- [x] Check Veena's abstract @baraaorabi
- [x] Reach out to R-ladies workgroup for R project co-lead @klgray25 

### Participant Application Prep
**Deadline: Mon. August 13th to send out first wave of emails**
* [ ] Start google-doc where @hackseq/hs18_org can add departmental/organizational email lists we can send hackseq advertisement to. ( @klgray25 )
* [ ] Draft email advertising hackseq participant recruitment ( @klgray25 --> need media? @ababaian)
* [x] Share link to participant application form for everyone to review ( @klgray25 )
* [x] Start an issue to coordinate advertising ( @klgray25 )

* [x] Create project description pages for the website ( @ababaian ) 
* [x] Update the hackseq mailing list for part. email ( @baraaorabi  )

**Comment by jenjaelin** [comment]
@emreerhan I've coalesced the questions down to 8 on the second page of [this document](https://docs.google.com/document/d/1WzP-s2bGyHGlH0ySC9IddW9mwEo0opctEt6C62PG4rY/edit?usp=sharing)

**Comment by emreerhan** [comment]
Draft email for contacting team leaders:

> Hi \<name\>,
> 
> We're \<interviewer1\> and \<interviewer2\> from the hackseq organizational team this year. In order to learn more about your project and to talk specifics, we want to schedule a 30min video chat with you. Do you think you can find the time to chat with us over the next two weeks? If so, what times work best for you?
> 
> Thank you,
> 
> -  -  -  -  -  -  -  -  -  -  -  -
> \<interviewer1\>, hackseq18 organizer
> \<interviewer2\>, hackseq18 organizer
> www.hackseq.com  |  @hackseq

**Comment by ababaian** [comment]
Which document should we send with sample questions?

**Comment by jenjaelin** [comment]
@ababaian pull the last page of the interview questions doc into a separate document to send.

**Comment by jenjaelin** [comment]
Also for everyone: I updated the interview sign-up sheet with 2 new columns to keep track of who's been contacted and scheduled times when they are put up (just the date is fine). Please update so I can keep track of when the interviews are expected to be done :)

**Comment by emreerhan** [comment]
Bruno says he'd be happy to host a git workshop for us :)

**Comment by jenjaelin** [comment]
Reminder to vote for a meeting date! Currently looks as if the top 2 contenders are July 26th and 30th. If we don't have any new votes by the end of the day, I'll set it for July 30th to give everyone the max amount of time to get those interviews in.

Cheers,
J

**Comment by jenjaelin** [comment]
Hi all, set the date for July 30th (6pm) at BCCRC as per usual. I won't be there, but if you guys find that most of the interviews won't be completed by then, feel free to schedule another date.

Cheers,
J

**Comment by jenjaelin** [comment]
Heya! Reminder to remind interviewees if you haven't heard back from them yet. Also, don't forget to submit items for the meeting agenda :)

@emreerhan, have you heard back from the couple of people who said they'd submit a project yet?

**Comment by emreerhan** [comment]
@jenjaelin we've received a project abstract from the ECOSCOPE team. They may ask to lead a team with only ECOSCOPE members. We're still discussing this with them.

I've emailed Allissa Dillman from the NIH about her project. I didn't receive an email from her yet, but I also didn't receive an "out of office" email either. I'll remind her again soon.

**Comment by klgray25** [comment]
Hey everyone! Could you please give a 2-3 sentence project summary for the projects you interviewed for? Either get this from the team lead or if you think you can summarize it yourself in a few sentences after having your meeting that works too. If they went into the same document as the interviews are organized in that would work well. I would like these for the participant applications. Currently, there is not a lot of consistency to the abstract lengths. 

I am looking for 1 line of background/justification/problem statement. Then 1-2 lines to explain the premise of the project. I know that's not a lot, but I think it's best to keep it short - people aren't going to want to read ~10 full abstracts.

Hope this isn't too much to ask! I'd do this myself, but the interviewers probably understand each project better and are less likely to mis-convey the project premise. I think people would do a better job handling this for a project they've discussed in detail. 

Thanks!
Kristen

**Comment by ababaian** [comment]
@klgray25 Me and Baraa didn't get these. Can we (@emreerhan) just send one email to all the team leaders and gather all the information at once? I have a few things I'd like for the website. We can get everything at once. #19

**Comment by klgray25** [comment]
Sure! Sounds good to me. I understand that for some projects with later abstracts, we won't be able to get these right away. However, I would like them as soon as possible so that we can open the participant applications. Can we compile a list of things to ask the team leaders for in the next few days so that we can send that all out together?

**Comment by emreerhan** [comment]
@ababaian that sounds like a good idea. I'll work on it.

**Comment by ababaian** [comment]
@hackseq/hs18_org See you all tonight!

**Comment by ababaian** [comment]
@hackseq/hs18_org See you all tonight!

**Comment by bfjia** [comment]
yikes, forgot about this. I got a deadline tonight so i'll be unlikely to attend.
@SweetiePi and I interviewed rob Gilmore. the project seems pretty interesting and fitting for a hackathon. I think Alex could update you guys with that.
Abcellera have 2 mentors coming to network instead of running a team. but they do have ppl who are interested in joining as a team member though.

**Comment by NoushinN** [comment]
Hi everyone :) a hackseq facebook page is set-up under hackseq hackathon, please feel free to invite friendships! I will be making an event page soon...feel free to login yourselves and craft things...or give suggestions here.

**Comment by ababaian** [comment]
@NoushinN There's a good chance the account will be taken down. You can't have an organizational account in facebook (it's their user policy), what we need is a facebook page for hackseq. You'd have to start it from your own facebook account (I think, I don't have facebook so I'm fuzzy on the details).

**Comment by jenjaelin** [comment]
hey all, did you talk about when to have the next meeting? So I can go about getting things prepped with doodle and to do lists :)

**Comment by ababaian** [comment]
We 100% did not.

**Comment by baraaorabi** [comment]
When are we going to have our next meeting? Did I miss that? Or we still don't have a time set up?

**Comment by ababaian** [comment]
Maybe let's do a meeting next week @jenjaelin and we can discuss meeting schedules after that.

**Comment by jenjaelin** [comment]
sounds good. I will get the doodle up and running in the next hour :)
