### ISSUE TITLE
Participant Applications

### ISSUE THREAD

**Issue by klgray25** [hackseq/hackseq18#21]
## Advertising ##

The participant applications are open and ready to be sent out. The example emails below can be used as a guideline. Be sure to also include the gameboy add image prepared by Artem!

If you send out an email advertising the participant applications, please track that [here](https://docs.google.com/spreadsheets/d/1EQK2iUrEQ57R-Txd-YTpB-dAqKB2aJ0oiW4cq00b1Wg/edit?usp=sharing). Also, if you are about to send an advertising email, please check the spreadsheet first so that we don't spam people!

The form can be found at the following link: https://goo.gl/forms/99UyiOlHlFmImodD2
Please make sure your hyperlinks in all emails are working!

### To Dos for Everyone ###

- [x] Review application form and provide feedback
- [x] Provide feedback on advertisement emails

### Application ###

The application for participants can be found [here](https://goo.gl/forms/dlYUQ23c37Ibz9uG2). (Note: You'll need to be logged into the hackseq account to see it, as the application isn't opened yet).

Please read it over and let me know if there are any changes you'd recommend. I have yet to finish adding the short abstracts, so those will be updated as they become available. I'll comment to let you know when the final form is ready for review.

### Advertising Email ###

If you want a quick template for what to say when reaching out to people to ask them to send around an email, this should work well:

Hello INSERT-CONTACT-NAME,

I'm helping to organize hackseq18, a genomics hackaton happening in October here in Vancouver. Would you please help us get the word out about the event and recruit participants by forwarding the following message to the INSERT-DEPARTMENT/ORGANIZATION-NAME.

Kindest regards,
INSERT-YOUR-NAME, hackseq18 Organizer
Twitter.com/hackseq (#hackseq18)
Hackseq.com

#### This is the main email for advertising: ####

Participant applications are now open for hackseq18 and we're looking for scientists like you to get involved in the event! Hackseq is a genomics hackathon happening in Vancouver at UBC campus from October 12 - 14. You and a team of 5-8 other participants will have an opportunity to work towards a solution for one of the exciting projects submitted for this year!

If you would like to participate, you can submit an application [here](https://hackseq.github.io/hs18/2018/03/15/participants.txt.html), or visit our website for more information at [hackseq.com](https://www.hackseq.com). Feel free to contact us if you have any questions at hackseq@gmail.com.

**Comment by ababaian** [comment]
Does anyone have any cool looking data files? Maybe something from a high-throughput experiment which looks out of the ordinary? If you do email it to me and I'll see about incorporating it, I'm running a little low on cool data images at the moment.

## Gameboy Ad
![hackseq18_gb](https://user-images.githubusercontent.com/9220907/43865530-b82eda4c-9b17-11e8-83da-099c93693eac.png)

*more options coming up*

**Comment by NoushinN** [comment]
Hi @ababaian, recently found this twitter page https://twitter.com/accidental__aRt posting data visualizations when they go beautifully wrong, some are interesting looking?

**Comment by ababaian** [comment]
I've changed the Project selection question from a multiple-choice grid to 3 pull-down rank questions. I think having numerical choices of numbered projects might lead to a few mis-choices. This also keeps the names associated with each project number.

Edit: LOL @NoushinN that's like the 100% opposite of what I'm looking for but it's hilarious.

**Comment by klgray25** [comment]
Good point! The changes sound good to me.

**Comment by ababaian** [comment]
Are the applications ready? I've got the application page online: https://hackseq.github.io/hs18/2018/03/15/participants.txt.html

**Comment by baraaorabi** [comment]
I just finished updating the maillist so that is ready. I read through the application. It looks great. One thing though, do we want to know whether the participants are going to attend physically or remotely?

**Comment by ababaian** [comment]
Really good point Baraa, we should also have a question to make sure they are certain that they can attend all three days October 12, 13th and 14th with ~hours.

**Comment by klgray25** [comment]
Great point Baraa. I will add that.

I was going to hold off until Wednesday, as we are still waiting on the last few project descriptions and Emre was expecting to hear a definitive yes or no from Allissa in the next few days.

The page with all of the projects online looks great by the way @ababaian!

**Comment by NoushinN** [comment]
yes agree, great page @ababaian 👍   just a minor typo, my name is spelled wrong though it's nabavi, not sure how to correct

**Comment by alexsweeten** [comment]
@ababaian Nice projects page!

One concern I have is that participants might be too lazy to scroll and find the other projects. This might unnecessarily skew the distribution towards projects 1 & 2 as opposed to 8 & 9. Maybe right at the top above Skill Proficiencies we can have the titles and links to all 9 projects so people see them right away.

**Comment by NoushinN** [comment]
@klgray25 I can't seem to access the participant application but thinking how we could increase retention rate and have 100% attendance on the day of hackathon, like having a sort of incentive? based on my reading of previous year, half of participants didn't show up on the day of, is this right @ababaian? maybe a topic to brainstorm in organization meeting

**Comment by ababaian** [comment]
About 1/8 or so for real life participants and about 1/2 for remote participants. We discussed this at one meeting but it will be worth talking about again how to incentivize people  to come. Participant application isn't online just yet, you have to login through the hackseq account to see it.

@SweetiePi fixed the projects page

**Comment by smaslova** [comment]
Also worth noting that last year one of the projects was cancelled at the
last minute, and we had 9 projects total, so that might account for a lot
of the no-shows.

**Comment by klgray25** [comment]
@NoushinN Yes, the application is not yet open. If you want to give feedback, please log into the account and take a peak at it! I'll open it up at the end of the day today even if we don't receive a response from the other team leads. I can substitute the information from the original team lead applications for now.

**Comment by alexsweeten** [comment]
Awesome @ababaian looks good!

I'm in favor of having a small participant fee to incentivize, around the $10 range. Participants could get a goodie bag of swag for it (assuming they're not remote)?

**Comment by klgray25** [comment]
We also don't want to de-incentivize people from coming. Also, we would have to set up a way of collecting the $10 from everyone, which would be a hassle. I think it kind of goes against the inclusive nature of hackseq too. Sorry, Alex! Don't mean to shoot down the idea too much - just my opinion on the matter.

The promise of free food and swag is probably sufficient to draw people in I would think. There won't be any way of completely guaranteeing that participants show up no matter what we do.

**Comment by alexsweeten** [comment]
Haha its ok! I agree, better to be inclusive.

**Comment by ababaian** [comment]
We should still discuss methods to incentivize people at the next meeting.

**Comment by klgray25** [comment]
Hey guys! I updated the main comment for this thread above with info about advertising. The participant applications are now open for submission. I will be sending out emails to a few departments at SFU, our mailing list and the SFU-UBC Bioinformatics program later this morning, so don't worry about those. If others could help handle the UBC departments that would be great. @NoushinN please start advertising on social media and let me know if there is anything else you need from me for that!

**Comment by NoushinN** [comment]
Great thanks @klgray25 ! 👍

**Comment by smaslova** [comment]
Has anyone sent out the participant applications to any UBC departments yet?  If not, I'll start doing that ASAP!

**Comment by klgray25** [comment]
Hey @smaslova, I don't think so. I have a spreadsheet [here](https://docs.google.com/spreadsheets/d/1EQK2iUrEQ57R-Txd-YTpB-dAqKB2aJ0oiW4cq00b1Wg/edit?usp=sharing) (also linked in the original post above) that I am asking people to use to record where they have sent the emails out. If you can start sending to UBC departments that would be great!

**Comment by klgray25** [comment]
@baraaorabi @SweetiePi would one of you mind hitting the Math and Stats, and Computing Science departments at SFU?
