### ISSUE TITLE
9th Organizational Meeting - Thursday Sept. 6 at 6PM *Minutes updated

### ISSUE THREAD

**Issue by jenjaelin** [hackseq/hackseq18#23]
# Minutes
### **Next meeting: BCCRC Thursday Sept 13th 5PM**
Please make it a priority as we are at ~5 weeks from the event

## Swag
- stickers have 2-3 different versions?
- notepads (tear off)
- t-shirts for organizers (?)
- [ ] **Artem** to look into swag

## Volunteers
- have participants/TLs volunteer for skills
- registration - keep open
### R sessions
- will have someone for sure on Friday, will likely have someone for other two days
- put tutors under community sponsors
- room use will be discussed later (post Sept 15)

## Sponsors 
- no updates

## Participants Applications
- advertise to senior bioinformatics profs (local)
- 66 applicants

- [ ] **Emre** to contact TLs to inform them that we have large numbers of undergraduates
- current plans to cut off on the 21st
- Bara to ask Shawn about the code for sorting participants
### Participant Committee
- Kristen, Bara, Venus, Jenny

## Logistics
- [ ]  **Sasha** sent out a few emails for quotes on social and lunches
- [ ] letter for sponsorship
- [ ] theatre room - double check request

## TLs
- confirm that TLs are coming
- have them start preparing packages to give participants

### closing
- historically - open google vote and have all participants give 1-3, go by people's choice
- presentations 5 min and ask for slides 
- start pres at 3:30 - present prizes before 5
- have 200 word abstract for finished project
### prizes
- TBD
### Next Meeting 
- [x] **Jenny** to make meeting time for every week

**Comment by ababaian** [comment]
@hackseq/hs18_org See you all tomorrow at BCCRC!

**Comment by alexsweeten** [comment]
Unfortunately I can't make today's meeting.

For updates on my end: I've contacted the Student Biotechnology Network, who will advertise for hackseq on twitter and in their next newsletter, as well at the SFU CS department.

**Comment by jenjaelin** [comment]
yeah no prob! add it to the agenda?

**Comment by NoushinN** [comment]
hello all, I am unable to make it to Vancouver as well, my updates: I did talk with Alex, president of postdoc association and he has kindly approved our participation call poster on their upcoming newsletter/twitter

**Comment by emreerhan** [comment]
Hi all, I won't be able to make the meeting today either. For my updates: I've reached out to the Computer Science Student Society at SFU. I'm still waiting on UBC for wifi at the event. If they don't get back to me by the end of the week I'll send another email to remind them.

**Comment by jenjaelin** [comment]
For everyone unable to make it, can you take a minute or two and think of if there is anything that you need us to discuss/assign out to do during our meeting (beyond just updates). Thanks!

J

**Comment by vlauu** [comment]
Where in the CRC are we meeting?

**Comment by ababaian** [comment]
Just to check; is someone replying to the participant emails we're getting on the hackseq email account?

If so can you 'archive' the emails you've dealt with so they are out of the inbox and we don't duplicate responses?

@klgray25 @baraaorabi
