### ISSUE TITLE
GSC computing resources meeting

### ISSUE THREAD

**Issue by bfjia** [hackseq/hackseq18#24]
I got in contact with Lance at the GSC to support our computing needs for hackseq. He's requesting a meeting in the 2nd week of September to discuss responsibilities and timelines.

Unfortunately I will not be here during that time, @emreerhan @klgray25 can you guys take this meeting since you guys are organizing the teams. It seems like he needs a list of how many accounts needed and how much resources is needed plus other informations.
I will forward you into the email chain and introduce you guys to Lance if you guys are good.

**Comment by klgray25** [comment]
That's fine with me.

**Comment by emreerhan** [comment]
Hey, yes you can put me in contact too. Please use my bcgsc email address: eerhan@bcgsc.ca
