### ISSUE TITLE
Letterhead

### ISSUE THREAD

**Issue by smaslova** [hackseq/hackseq18#25]
@ababaian do we have a designated font?  Or ideally a whole letterhead design?

**Comment by ababaian** [comment]
Give me 24 hours and I can do this : )

**Comment by smaslova** [comment]
Thanks! Something like this would be great since I'll be printing it out in black and white:

![image](https://user-images.githubusercontent.com/32580603/45233611-26bcbd80-b288-11e8-8b6b-3876f4bd4e3c.png)

**Comment by ababaian** [comment]
Here's the letterhead; let me know if that'll do : )

[hackseq_letterhead.docx](https://github.com/hackseq/hackseq18/files/2362532/hackseq_letterhead.docx)

**Comment by smaslova** [comment]
That's great, thanks Artem!
