### ISSUE TITLE
hackseq Organizers T-shirts

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseq18#26]
Hey @hackseq/hs18_org 

For the t-shirts for organizers we have a few options for colors/prints. If you're all OK with it; I would say we go with black logo and I'll hand [tie-dye](https://cdn.instructables.com/FIA/WZ27/IDUQWGCR/FIAWZ27IDUQWGCR.LARGE.jpg?auto=webp&width=789) the shirts to make them stand out. Else vote below and we can make them acccordingly

# T-shirt order form

The poll was pretty but someone didn't fill it out and I don't know who. Easier if we simply go with a [spreadsheet](https://docs.google.com/spreadsheets/d/1sWxoK50U_fBqe4E9djoWhKyj7QxOA39GjtaCxvWaCBk/edit?usp=sharing)

**Comment by baraaorabi** [comment]
I like these GitHub polls!

**Comment by NoushinN** [comment]
same! how is this done?! 🥇

**Comment by ababaian** [comment]
I used [this website](https://app.gh-polls.com/)

**Comment by jenjaelin** [comment]
This is awesome! Let me know if you want any help with it? FYI there's also a cheap "silk screen" technique that can be done with a plastic bag and iron as stencil if anyone ever wanted to do it. [How to here](https://diaryofaneastyorker.wordpress.com/2013/04/11/diy-shirt-designs-how-to-make-your-own-freezer-paper-stencils/)

**Comment by ababaian** [comment]
@hackseq/hs18_org sorry to spam but can you re-enter your T-shirt data on the google doc: https://docs.google.com/spreadsheets/d/1sWxoK50U_fBqe4E9djoWhKyj7QxOA39GjtaCxvWaCBk/edit?usp=sharing

**Comment by jenjaelin** [comment]
FYI - it is highly likely that white font will get dyed in the tie-dye process/can't read due to white patches so we might just be defaulted to black font for tie-dye shirts

**Comment by ababaian** [comment]
Yes you're correct. Regardless, I'm thinking we dye the shirts first and then return them for printing. We could in theory do a white print with that but it would require an immaculate dye job which is probably harder then it sounds :smiley:

**Comment by ababaian** [comment]
Sorry about the spam everyone but can you take a minute to fill this out with the new choice between T-shirt or Crewneck sweater?

[T-shirt Survey](https://docs.google.com/spreadsheets/d/1sWxoK50U_fBqe4E9djoWhKyj7QxOA39GjtaCxvWaCBk/edit?usp=sharing)

@klgray25 @jenjaelin @SweetiePi @baraaorabi @NoushinN @vlauu @imasianxd @emreerhan @smaslova

**Comment by jenjaelin** [comment]
@ababaian any chance I can order a black crewneck as well? I'll pay the fee for it :)

**Comment by jenjaelin** [comment]
also, sent in a request for turn around time if we pick up. If I don't get a reply by tomorrow morning I'll make a call to them. If pick-up isn't allowed, I'll order online and the delivery is 2-6 business days.

**Comment by jenjaelin** [comment]
update: called in and they said has to be delivery. I'm just gonna guess that the last two will also be crewnecks and make the order?

**Comment by ababaian** [comment]
Sounds good to me. We need to have all the shirts delivered by Monday the 8th the latest to have it printed on time.

**Comment by jenjaelin** [comment]
should be fine. I'm about to send in the order right now. They don't have XS as a size so I'm just ordering S's for those. (Sorry!)

**Comment by emreerhan** [comment]
@jenjaelin if it's not too late, can you also add a black medium t-shirt with a white logo for me as well (the same one as yours). I'll pay for it too.

If it is too late, it's ok

**Comment by jenjaelin** [comment]
@emreerhan nope still fine! added

Can someone let me know if there is an account to bill this to (by email/in private). if not I'll bill it to myself and get a receipt.

**Comment by emreerhan** [comment]
I believe we've been paying for things on our own, to be reimbursed later. That's how @ababaian is paying for wifi.

**Comment by jenjaelin** [comment]
cool cool
 making the order now!

**Comment by ababaian** [comment]
Hey @jenjaelin do you know how long the delivery will take? If we get the shirts in to the printer by the 1st then we're good. If we get it in by the 8th then there's a $50 extra fee.

**Comment by jenjaelin** [comment]
@ababaian supposedly 2-6 business days and ships out day of if ordered before 11am which I did. So theoretically they should all arrive sometime this week or midway through the next.

**Comment by ababaian** [comment]
That should be OK in theory : ) If it comes this week, the weather is good this weekend and I have some free time. I could do the tie-dye this one afternoon this weekend so we have everything done by Monday and we don't have to pay the Rush order costs. If this doesn't work out then we just need to do it some time next week/weekend and we pay the difference.

**Comment by jenjaelin** [comment]
got the shipping confirmation today! fingers crossed it'll come in this week

**Comment by ababaian** [comment]
Did it arrive yesterday @jenjaelin ?

**Comment by jenjaelin** [comment]
![image](https://user-images.githubusercontent.com/37309499/46231427-b81bce80-c320-11e8-89eb-54f096105c36.png)
-.-

**Comment by ababaian** [comment]
`-_-

**Comment by jenjaelin** [comment]
It arrived!!! Can you come pick it up in the morning??

**Comment by ababaian** [comment]
Yep! I can. @jenjaelin + @klgray25 + anyone else, if you're up for making the tie-dye tomorrow let's do it around noon. I'm stoked for a lazy few hours futzing around with this.

**Comment by klgray25** [comment]
I can do around noon. Where?

**Comment by ababaian** [comment]
@jenjaelin Give me a shout when to pop by and pick up the shirts!

**Comment by jenjaelin** [comment]
Last load in the dryer right now but I'm out currently.  Best is probably after 7 or so?

J

**Comment by jenjaelin** [comment]
Hey! I'm actually home now so feel free to drop by whenever :) 

J

**Comment by ababaian** [comment]
KK Jen; I'm OMW now.

**Comment by ababaian** [comment]
See #39
