### ISSUE TITLE
URGENT. Need address for package delivery

### ISSUE THREAD

**Issue by bfjia** [hackseq/hackseq18#28]
Hi all, 
I'm out of town right now but the mugs came through FedEx and it requires a signature. I need to redirect it to a place where someone can someone is able to sign for it. 
Let me know asap please.

**Comment by jenjaelin** [comment]
errr... when's the expected time of delivery? And can it be sent to a Canada Post PO box to be signed on delivery?

**Comment by bfjia** [comment]
As soon as possible. I need to call in today
And no, it has to be signed at door.




-------- Original message --------

**Comment by jenjaelin** [comment]
shit :/ I guess 2 other questions. 1) how many mugs are being delivered and will they deliver to an institution? cuz I can just give you the address to BCCHR and hide them in my office if it's not a huge number.

I guess question 3 is how soon is soon for delivery. like within the next hour?

**Comment by bfjia** [comment]
Around 50mugs if I remember correctly so it is a big package. I think they are able to deliver to institution.
Delivery can be the next day but should be asap.



-------- Original message --------

**Comment by jenjaelin** [comment]
Okay. Ummm... I'm not sure how to deal with the package when it gets here but I'll figure it out if need be. In case no one else can give you something, my number is (519) 498-1555 and you can have it delivered to entrance 18 at BCCHRI (950 W 28th Ave, Vancouver, BC V5Z 4H4). Have them call me and I'll meet them in the entrance. If they can guarantee delivery before 10am tomorrow, I can also have it delivered to my house. Which is 5459 Main St. Vancouver. The latter would be preferable.

**Comment by vlauu** [comment]
The mugs arrived at the Brinkman Lab at SFU. Will probably need someone with a car (I don't)  to deliver them to hackseq - the box is quite heavy and huge

**Comment by bfjia** [comment]
That was fast. I'll move it after.

Can someone close this issue


-------- Original message --------
