### ISSUE TITLE
Participant sorting

### ISSUE THREAD

**Issue by baraaorabi** [hackseq/hackseq18#30]
I created this Jupyter [notebook](https://github.com/hackseq/hackseq18_private/blob/master/participant_sorting/participant_sorting.html) (you need to open it Raw, and save it as HTML file, and then open it in your browser) to help us know big picture before we decide on how to sort participants into teams. If you want me to add some more plots, let me know!

**Comment by ababaian** [comment]
How to spot a data-nerd in the wild <3

**Comment by NoushinN** [comment]
Let's make some publication figures out of your great work @baraaorabi  💯 👍 :)
