### ISSUE TITLE
Hackseq18_Publication_Skeleton.md 

### ISSUE THREAD

**Issue by NoushinN** [hackseq/hackseq18#31]
*Topics to think about for our publication, please add organs, muscles, tendons as you see fit*

# Hackseq past, hackseq present   
* who we are as organizing committee
* Where were we with hackseq
* where are we going?

# Team-lead selection 
* Thoughts on interviewing teams 
* @ everyone: Let's reflect on our interview experiences and elaborate on positive/negative aspects
* Team lead Pre-Survey de-identified data analysis

# Participant selection
* Participant Recruitment Questionnaire reference + de-identified quantification 
* @klgray25 's  reflections, and suggestions
* @baraaorabi 's beautiful python charts   
* Participant Pre-Survey de-identified data analysis

# Team assembly
* Participant Recruitment Questionnaire reference + de-identified quantification 
* hackseq's organizational support 
* @ everyone: procedures, progresses, failures, thoughts, reflections    

# Eight Lessons from eight projects
* @ everyone: organizing team members's reflections
* Input from final survey analysis of participant's and team lead's experiences   
* De-identified post survey data analyses + discussion

# Concluding statements 
* @ everyone: reflections and what can we improve on going forward  
* Future suggestions on improvement of processes

# Acknowledgements
* Thanks to our sponsors
* Who are they? could you please list? @vlauu   

# References
* Inspiration from [Hackseq16](https://f1000research.com/articles/6-197/v1)

**Comment by ababaian** [comment]
Probably one of the most important things from the last publication as having a "User Experience Survey". Getting objective numbers from participants on how they felt beforehand and how they experienced hackseq (see [Figure 3](https://f1000research.com/articles/6-197/v2)). Can we gather data before hackseq and then more data after hackseq about expectations/experiences so that we can see how we did?

Is there a question or central thesis for this publication? What do we want to say which hasn't been said before?

Relevant References
- [hackseq Publication](https://f1000research.com/articles/6-197/v2)
- [Hack weeks](http://www.pnas.org/content/115/36/8872)
- [NESCent](https://f1000research.com/articles/6-786/v1)

**Comment by NoushinN** [comment]
That's a great point, do you happen to have access to the survey questions from 2016? We could ask those exact questions for a longitudinal analysis of responses, but then also ask new ones to test efficiency of our own cohort. The NESCent and Hack weeks are great external comparisons. 

I can put a survey together soon and ask for everyone's sanity/improvement check and feedback..

**Comment by NoushinN** [comment]
Great points and refs. The NESCent project organization is so neat, [here](https://nescent.github.io/community-and-code/data/), maybe something we could model  

What do you all think of these survey questions pre/post hackseq18? Some need to be tailored depending on whether it goes to participants or leads  


# *Survey questions after hackseq18:*
* Please select your project number  
* Was your project's emphasis on software learning or on hackathon activities?
* Please rate the Git/Github info session's usefulness (0-5)
* How can the Git/Github workshop be improved?
* Please write three single word adjectives to describe your experience at hackseq18 (comma-delimited plz)  
* How did you find the 3-day (8h x 3) format of the hackathon? Too Long, Too Short, Just right  
* Rate your subjective experience at hackseq (0-5)
-Fun -> boring
-Uninformative -> Enlightening
-Hostile -> Collaborative
-Chaotic -> Organized
* What can we do at hackseq to improve the experience of future participants?
* What about hackseq did you enjoy the most?
* Would you participate in an event like hackseq again in the future? Strongly Agree, Agree, Somewhat agree, Somewhat disagree, Disagree, Strongly disagree
* Did you have a clear idea of the objectives/requirements of the hackathon based on the information provided in advance? Strongly Agree, Agree, Somewhat agree, Somewhat disagree, Disagree, Strongly disagree
* Would you consider leading a hackseq team (or similar) at a future event? Please explain.
* Would you be interested in helping organize a future hackseq event? Yes, YES!, No thanks, Maybe
* Do you think your experience at hackseq will lead to new opportunities beyond this event (e.g., collaboration, new research avenues, employment opportunities)? If so, please describe?
Strongly Agree, Agree, Somewhat agree, Somewhat disagree, Disagree, Strongly disagree
* Hackseq made you more comfortable in doing open science? Strongly Agree, Agree, Somewhat agree, Somewhat disagree, Disagree, Strongly disagree
* Which programming languages and tools did you and your team use during the course of hackseq? (Comma delimited please)
* I learned things at Hackseq that will help me in my day-to-day research: Strongly Agree, Agree, Somewhat agree, Somewhat disagree, Disagree, Strongly disagree
* I learned tools at Hackseq that were new to me: Strongly Agree, Agree, Somewhat agree, Somewhat disagree, Disagree, Strongly disagree
* I ended up teaching things to other people: Strongly Agree, Agree, Somewhat agree, Somewhat disagree, Disagree, Strongly disagree
* Briefly describe what were the computational requirements (e.g., AWS, ORCA, etc) for you during hackseq.
* Which resource(s) did you wish you had access to that was/were not provided?
* Please rate the usefulness of the various computational infrastructure (1 = no use, 5 = critical)
-ORCA (bcgsc)
-AWS
-Technical Support from Volunteers and Organizers
* Voting: rank the top 3 projects  



# *Survey questions before hackseq18:*  
* Full name
* How old are you? (age brackets)
* What best describes your ethnicity?
* What gender do you identify as? 
* What is your organization?
* What is your title?
* Which project are you interested in participating? List [for participants]
* Will you be attending?
* Did you attend previous year's hackseq events?
* What is your motivation for attending hackseq18? (0-5)
* How well do you understand your project? Very well, well, ok, not so well, no idea [for participants]
* How ready are you to lead? Ready, somewhat ready, not ready [for leads]
* How did you hear about our event?
* Do you find the event location easily accessible?
