### ISSUE TITLE
LAST Organizational Meeting - Thursday Oct. 11th post VanBUG  (7PM) **Please see To Dos!

### ISSUE THREAD

**Issue by jenjaelin** [hackseq/hackseq18#36]
# To Do:
### Food orders
- [ ] Kristen - Subway
- [ ] Justin - Starbucks Coffee
- [ ] Baraa - Chipotle

## Writing workshop
- [x] Jenny and Baraa to hash out plans

## Logistics and tasks 
- [x] Print out Attendee list organized by team / days people will show up for us to register people coming in and give out name tags (5x logos, 1 registration sign, 5x schedule)
- [x] Can someone bring a camera to take photos at the event?
- [x] manning registration: put 1 in front the participant name on the sheet [here](https://docs.google.com/spreadsheets/d/1DMg4l_zQwU-EVFThcWg9SpPwJsg3EP3aO1D6eyd3XOo/edit#gid=0)
- [x] meet/divvy food
- [ ] organizer meeting during day on Friday
- [x] set up/clean up
- [ ] Water boiler(s) for tea
- [x] split up who will be there in the morning Sat and Sun
- [x] etc

#Minutes
## Split organizers in morning
if you aren't on morning duty, show up ~lunch
### Fri 
- everyone at 8:00 am
### Sat 
- Sasha, Baraa, Emre
### Sun 
- Jenny, Justin, Artem - someone get breakfast food from Sasha

## Registration
- Venus, Jenny + Kristen

## food
- Sasha + Justin for coffee Friday
- Food pickup Saturday - Baraa + Sasha

## Meeting Friday
- tentatively 11am 
- discuss any logistics things
- plan out grant application group

**Comment by jenjaelin** [comment]
To Do lists are up!

**Comment by NoushinN** [comment]
here's a survey to send to team leads, participants, and organizing committee, please feel free to add/subtract/modify https://docs.google.com/forms/d/1aXHaO9QaGOte-eCrdDVntg6YQPraAC__DVs9MhHbBO4/edit?usp=drive_open&ths=true

**Comment by NoushinN** [comment]
and the haiku contest is advertised on twitter

**Comment by ababaian** [comment]
If it's OK the plan is to open the contest tomorow morning and I'll be able to post some Haiku right away. I can do this side of things on twitter / social media.

I've deleted the tweets for now.

**Comment by NoushinN** [comment]
sure, sounds good

**Comment by ababaian** [comment]
Sorry, I can't make the meeting guys. I'm taking a mushroom class and the first night got moved to Thursday 7pm. I can chat briefly before VanBug if there's something or if y'all need me to pick something up to drive to the event.

**Comment by jenjaelin** [comment]
Heya! I don't recall who was supposed to send out the reminder emails for participants and TLs, but those should probably be done later today or by early afternoon tomorrow? Especially if we want to give the TLs time to send stuff to their team as well.

**Comment by baraaorabi** [comment]
@smaslova Do you still need me to pay for Chipotle? Please let me know

**Comment by baraaorabi** [comment]
I'm drafting both email to the TL's and the participants. Should I have the Slack invitation added to the participants email?

**Comment by smaslova** [comment]
Chipotle needs to be picked up on Sunday and we'll pay for it then.

**Comment by vlauu** [comment]
@ababaian  MSFHR is sending us 25 pens + postcards. hopefully they arrive by the end of today...

**Comment by jenjaelin** [comment]
@baraaorabi probably a good idea to have it.

**Comment by baraaorabi** [comment]
If you haven't, please join the Slack

**Comment by jenjaelin** [comment]
brb while I download slack XD

**Comment by smaslova** [comment]
What's the workspace?

**Comment by baraaorabi** [comment]
https://github.com/hackseq/hackseq18_private/issues/22

**Comment by baraaorabi** [comment]
I won't be able to attend the meeting after VanBUG. Our lab mate is going back to Germany and we are going out after VanBUG to pay him farewells. I will be around CRC before VanBUG.

**Comment by baraaorabi** [comment]
I am down in CRC lobby if any of you guys is around

**Comment by jenjaelin** [comment]
@emreerhan oh no. the minutes didn't save ;_; sorry!!! hope you got what to print. idk what happened

**Comment by emreerhan** [comment]
I think I got all of that :)

**Comment by jenjaelin** [comment]
Hey all! If you're having trouble finding LSI, give me a call at (519) 498-1555 

See y'all in a bit! 
J

**Comment by vlauu** [comment]
Which atrium in LSI are we supposed to go?


On Oct 12, 2018, at 7:32 AM, jenjaelin <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey all! If you're having trouble finding LSI, give me a call at (519) 498-1555

See y'all in a bit!
J

**Comment by baraaorabi** [comment]
If it's just like last year, then it is the one with the big tables and
just vast open space.
