### ISSUE TITLE
Last email to TL's

### ISSUE THREAD

**Issue by baraaorabi** [hackseq/hackseq18#38]
Dear hackseq team lead,

Hackseq18 is just around the corner! 

The fabulous weekend will start **this Friday** at [East Atrium Life Sciences Institute (LSI)](https://goo.gl/maps/5VGpjdDW1D82) in University of British Columbia (UBC).

We will be there by **8:30AM** for coffee (and tea of course!) and snacks to sign you in too. The full [schedule](https://hackseq.github.io/hs18/2018/08/11/Schedule.html) of the event is now online. Please try to be there before 9AM, especially for the first day.

As a team lead, please ensure that:
- Your GitHub repo is setup and that all your team members are added to it with **write** access.
- Your Slack channel is setup, and you have added your team members to your channel.
- Computing resources:
  - Test your access to the computing resources
  - Share your login credentials with your team (maybe you wanna do this in person on the first day of the hackathon?)
  - Upload any datasets you might wanna use **BEFORE** Friday. Our WiFi setup will be good enough to support SSH terminal connections, but not for multiple massive datasets to be uploaded/downloaded at the same time.
 
We **strongly recommend** reaching out to your team members before hackseq starts, ensuring that no one falls through the cracks. You might wanna talk about:
  - Tools and software to have installed locally on their laptops (or at least to have a working SSH terminal working if they'll use the servers. I personally recommend MobaXterm for Windows).
  - Reading material that would get them on track to start hacking off the bat
  - Slack details (channel and invitation)
  - A nyan cat gif or one of our [awesome media](https://github.com/hackseq/hackseq18/issues/9)

Final thing regarding the projects, to 'complete' your project, by the end of hackseq you must have the following items prepared:
- GitHub repo README.md file to be updated and that would include basic description of the project, installation requirements and instructions, simple use and any parameter documentation. Check [chromeQC](https://github.com/bcgsc/chromeqc) as an example from last year.
- A 300 word [scientific abstract](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3136027/) for your project.
- A 3 minute presentation for Sunday's 3:30PM presentation session summarizing the project and the work progress and possible future directions.

We also highly encourage every team to have an [application note styled paper](https://github.com/bcgsc/chromeqc/blob/master/paper.md) describing the project. To help teams with this, we hold a couple of writing workshops with a designated member from each team to help them grind through the different writing parts including the paper.

Also, our [Haiku Contest](https://hackseq.github.io/hs18/2018/10/04/BioHaiku_Contest.html) is now open! Write and submit your [#BioHaiku](https://twitter.com/hashtag/BioHaiku?src=hash) for a chance to win an ancestry analysis kit! (or a bookstore giftcard if you rather that).

One final note, please remember to **BYOM** (bring your own mug) to hackseq if you want to have coffee/tea. 

Happy hacking!
hackseq18 Organizing Committee

**Comment by emreerhan** [comment]
You have my blessing

**Comment by bfjia** [comment]
+1 very comprehensive

**Comment by NoushinN** [comment]
yes agree, looks great! BUT
are we not sending a pre-hackseq survey to track how well we met the expectations after?? this will help with a story impact pub....

**Comment by ababaian** [comment]
Looks good, I just added that a scientific abstract is part of the requirements for completion.
