### ISSUE TITLE
Organization recruitment email

### ISSUE THREAD

**Issue by jenjaelin** [hackseq/hackseq18#4]
Below is a draft of the email for organization recruitment. All criticism is welcome.
------------------
Hi there!

hackseq is coming back for fall 2018 and we are currently looking for enthusiastic organizers to help make this happen. 

Hackathons gather the brightest minds who are always ready to learn and build something new just because they can. As organizers, our job is to bring the weekend to life and take care of the logistics so that the hackers don't have to. 

**Why be an organizer?**
Putting together an event as large as a hackathon is a lot of work, but it is also a lot of fun too. You will be working closely together with a crew of other organizers from varying backgrounds for 4 months; Warning - you will make friends. Along the way you will be asked to do (things) you have never done before, but that's how you learn right? If you like being challenged and want to put that to work to bring a marathon of a weekend to life, join us by sending an email to: hackseq@gmail.com.

You can also learn more about hackseq, explore past projects and join the mailing list to be updated when each application stage is open at http://www.hackseq.com

Hope to hear from you soon!
-- hackseq18 committee

**Comment by klgray25** [comment]
Just one quick correction from me! I think you missed a word in the third paragraph. It should be something like this:

Along the way you will be asked to do THINGS you have never done before, but that's how you learn right?

Not sure if "things" is the right word, but something needs to go there. Looks great otherwise!

**Comment by jenjaelin** [comment]
ah oops! I had "things" there before but didn't like the word and apparently subconsciously decided not to include a blank there either. 

anyone have any better suggestions?

**Comment by ababaian** [comment]
=D Looks good.
