### ISSUE TITLE
Debrief Meeting - Monday October 22, 6PM

### ISSUE THREAD

**Issue by jenjaelin** [hackseq/hackseq18#43]
# To Do:
- [x] [vote](https://doodle.com/poll/sgeydcv2e2k2hxax) on debrief date
- [ ] task write ups in the [wiki](https://github.com/hackseq/hackseq18/wiki)
- [ ] add things to agenda

# Agenda
- Send final follow-up Thank you email to Team Leaders / Follow up with Sponsors
- finalize budget
- how to build projects (apply as teams vs. apply as individuals)
- publications
  - funding possibility for Bruno's last year project for f1000 submission
- hackseq publication
- timing to coincide with conference
- MLH application
- Secure multi-year sponsorships in future years (i.e. 3-year option)
- Organizer dinner/activity
  - choose a date for (Sat/Sun) for Aviary + Dinner organizer party
- clothing/swag
- bank account
- Email all former hackseq organizers to review/add to the organizer wiki (Artem)
- Mailing list is >500 people -> Gmail allows 500 recipients at a time

# Minutes
## Emails
- send follow up email with thank yous + photos for Sponsors
-  get thoughts from TLs about what they thought for leading a team, what resources they would like in the future - Baraa to draft letter
  - include Noushin's workspace
  - make a wiki for TLs - give expectations for them before application
- put receipts into budget
- Gmail limit
  - currently have label for contacts to send out emails
- think about making an actual mail list - [MailChimp](https://mailchimp.com/) - Baraa will look into it

## Team structure 
- someone wanted to have own teams built already
- option of having TLs filling their team to an x percentage themselves?
- continue as we do now and take exceptions as they come

## Team Leads
- Emre to start with making wiki for TLs - ask Alex for perspective

## Publications
- yes for funding Bruno
- hackseq publication
  - purpose - focus on collaboration rather than competitive, how it enables the opportunity to work together, have publications
  - anything new to say - wiki, other resources we have - clone and use to build own "hackseq"
 - 5 years of hackseq
  - start putting together data now
  - start writing manuscript on wiki, what data we want etc.
  - i.e. Sankey plot for participants
- centralizing data

## Wiki 
-  finish up, polish
- think of making it less specific
- send out email to previous organizers when done so that they can review (Monday after deadline)
- deadline: Next Friday

## Conferences 
- look into bio(informatics) conferences next year for idea when we want to have a hackseq
  - BC Cancer conference - every fall - someone look up date 

### MLH
- min. 100 people
- write in a way to generalize 

### multi-year sponsorship
- possibly restructure to allow for it
- send it out with follow-up emails

## social
- rock climbing at aviary
- lunch and dinner slots for sat. and sun. in Nov. - Dec

## Shirts
-  http://www.artee.ca/products.html
- possibility of having $5 payment with RSVP

## Money things
- currently no issues with having Grasspods

**Comment by ababaian** [comment]
Include a bell to ring at the end of hte day to demarcate the end of the work period.

**Comment by jenjaelin** [comment]
Hey y'all! please vote on a debrief meeting date by the end of today if possible!

**Comment by baraaorabi** [comment]
We are missing 3rd day registration. Who has the paper?

**Comment by jenjaelin** [comment]
the last I knew of it, @NoushinN had it at the last table

**Comment by ababaian** [comment]
I have Day 3 registration, I will be updating it now.

**Comment by jenjaelin** [comment]
Hey all! Set the debrief meeting for next Monday at 6PM. Gives us a little time to get the written bits done but also not run too far into next week.

See y'all in a week!

**Comment by ababaian** [comment]
Heya gang,

I'm heading to The Hive tomorrow after this meeting. I'll take my car which is ~5 minute walk from CRC, if you're interested in coming bring some gym clothes / shoes and we can take a ride over together. All welcome : )

**Comment by alexsweeten** [comment]
Folks decided to visit me last minute, so unfortunately I can't make the meeting today.

**Comment by ababaian** [comment]
@hackseq/hs18_org the wiki updates are due today such that I can send out the email Monday morning.

**Comment by jenjaelin** [comment]
I thought we agreed on two weeks? I think I meant to write next next friday :x 

can someone confirm/deny if I'm crazy?

**Comment by ababaian** [comment]
Damn we did meet earlier this week... It's been a long week, I'm the crazy one.

**Comment by jenjaelin** [comment]
No worries lol. I also had the "oh no, we met two weeks ago and I'm way behind" moment.

**Comment by NoushinN** [comment]
how are we doing here? anything pressing? I am still coming to terms with hackseq18 inactivities
