### ISSUE TITLE
Date of Hackseq18

### ISSUE THREAD

**Issue by emreerhan** [hackseq/hackseq18#8]
Hi all,

I think we should discuss which weekend we want to hold Hackseq18 before sending out the team leader application request email. In October our options are:

- October 5-7 (note: October 8 is thanksgiving)
- October 12-14
- October 19-21
- October 26-28

I think October 12-14 or 19-21 make the most sense. Maybe we can make a poll and democratically choose a date after some discussion.

**Comment by alexsweeten** [comment]
Hey everyone,

I've done some digging and haven't had much luck with finding a genomics or CS related conference in Vancouver that overlaps with our planned dates. The only tangentially related one I did find was the RecSys conference on recommender systems (https://recsys.acm.org/recsys18/), which I wouldn't recommend as it's during Thanksgiving weekend.

**Comment by jasgrewal** [comment]
Sorry to butt in but very far-out-there idea: perhals consider reaching out to Will Hsiao, he is planning on a metagenomics / bioinfo conference in the city next year but if they have registrants early on by oct, perhaps you guys can hold a pre-conference hackathon or sthing?

**Comment by NoushinN** [comment]
Also butting in here but BC Tech still has some room for exhibitors in their May summit, not sure how much it costs but we may be able to book a table to advertise hackseq https://bctechsummit.ca/exhibitors/

**Comment by alexsweeten** [comment]
@jasgrewal Thanks for the suggestion! I have a meeting with Will tomorrow and can talk to him about it.

I've also reached out to my friend Jeff, who runs communications for Vancouver's [Student Biotechnology Network](http://www.thesbn.ca/) . They might be able to plan an event in tandem to HackSeq, or at the very least help advertise :)

**Comment by ababaian** [comment]
We should know a date in a few days; @smaslova got the contact person, we'll wait to hear back.
