### ISSUE TITLE
hackseq18 Art & Media

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseq18#9]
I'm continually going to revamp some of the art and media on the website over the coming months. If you have any artistic abilities and want to help out with some aspect then feel free =D
I'm not particularly artistic so I lean heavily on making pretty graphs and then stylizing them.

*(work in progress)*

# [Core Design Assets](https://www.hackseq.com/design-assets/)

#### 80S Ribosome Retrowave
![80s_retrowave](https://user-images.githubusercontent.com/9220907/38403176-59eded1e-3916-11e8-9bff-07b0769dc779.jpg)

![Poster Retrowave](https://raw.githubusercontent.com/hackseq/hackseq18/master/media/80S_letter.jpg)

![Solo cup wireframe](https://raw.githubusercontent.com/hackseq/hackseq18/master/media/hackseq_title_solo.png)

![Vancouver Skyline Abstract](https://raw.githubusercontent.com/hackseq/hackseq18/master/media/background_van.png)
## Social media catchy images

![tRNA Rotation](https://raw.githubusercontent.com/hackseq/hackseq18/master/media/tRNA_rotation_scan.gif)

![tiredformatician](https://raw.githubusercontent.com/hackseq/hackseq18/master/media/tiredformatician1.gif)

![drawHelix script](https://raw.githubusercontent.com/hackseq/hackseq18/master/media/drawHelix.sh.gif)

#### The Ramones
![ramones_hs18](https://user-images.githubusercontent.com/9220907/38403141-2141f6cc-3916-11e8-8aaf-9dc16c865705.png)

## Other media

- [Email Signature Pack](https://github.com/hackseq/hackseq18/files/1925968/hs_email_signiture.zip)

**Comment by jenjaelin** [comment]
Hey! I do a bit of digital work, have some photoshop skills and a drawing tablet. Let me know if you want help designing anything from scratch :)

**Comment by ababaian** [comment]
=D Nice nice @jenjaelin 

I'd 100% be down for working together. Take a gander around the website and let's improve the art. I wrote a basic [Style Guide](https://github.com/hackseq/hackseq_2017_Private/blob/master/website/hackseq_StyleGuide.pdf) for hackseq.

Some of the things which would be nice are: Letterhead  for sponsorship / thank you letters. Slides which we can use to advertise hackseq at different events like VanBug. Or image "flyers" for sending out departmental emails. If we create a set of artwork which we can use in these different contexts then we'll be set =D

I guess we should focus our energy on specific objects once once we have a a need for it: if anyone needs anything particular designed let us know!

**Comment by jenjaelin** [comment]
Will do! Have anything particular in mind already besides the above? I'm swamped until Wednesday but after that we can mayhaps meet up and do some doodling if there was anything immediate that we wanted to have.

**Comment by ababaian** [comment]
What would be good is some Twitter/Facebook sized images or gifs we can use during Team Leader Recruitment. We could use some catchy art that would work for that.

**Comment by jenjaelin** [comment]
Things we need
T-shirts 
wallpapers
banners
splash page
Pixel art - draw something new

Edit:
Sticker / Band Logo Design

**Comment by jenjaelin** [comment]
![image](https://user-images.githubusercontent.com/37309499/38956799-865c8b8e-430d-11e8-9e8a-39f3a28cc75d.png)
anyone remember 90s solo cups?

**Comment by ababaian** [comment]
@hackseq/hs18_org 

As requested: email signature pack (2 examples) 

[hs_email_signiture.zip](https://github.com/hackseq/hackseq18/files/1925968/hs_email_signiture.zip)

**Comment by bfjia** [comment]
both signatures looks pretty good (Y)

**Comment by ababaian** [comment]
## Request: [Team Leader Slide](https://github.com/hackseq/hackseq18/issues/6)

Anyone up for doing this?

**Comment by NoushinN** [comment]
I am really liking the ramone's theme, I can put something together, but what is the text I should promote?

**Comment by jenjaelin** [comment]
probably the following:

- Date of event
- What it is
- Why/who should apply
- Deadline for applications
- link to more info

**Comment by ababaian** [comment]
I think a reworked version of hte email text

**Comment by alexsweeten** [comment]
![rise-against-hack-seq](https://user-images.githubusercontent.com/7028404/39145873-f3f72b4c-46e9-11e8-9e1a-4ed128109fc2.png)

Had some time to kill and whipped up a Rise Against theme.

**Comment by ababaian** [comment]
@SweetiePi That's sick man.

**Comment by jenjaelin** [comment]
That looks awesome!

**Comment by alexsweeten** [comment]
![pokemon-hackseq](https://user-images.githubusercontent.com/7028404/39203916-10b74840-47ab-11e8-903d-0ee118e9f6b5.jpg)

Experimented with a Pokemon theme, fits a little more to the 90' aesthetic.

**Comment by ababaian** [comment]
Man you're killing it @SweetiePi. One general note though hackseq is one word, first `h` is lowercase whenever possible, so maybe hackSEQ. ;)


OK:  `hackseq`, `HACKSEQ`, `hackSEQ`, `hackseq18` ...

Avoid: `Hackseq`, `HackSeq`, `Hackseq2018` ...

Edit: Also I'm uploading high resolution images for us to use at `https://github.com/hackseq/hackseq18/tree/master/media`

**Comment by alexsweeten** [comment]
@ababaian Sure thing. I'll fix that up in the previous two images.

Also if no one has claimed the team leader slide, I can finish that up by today.

**Comment by jenjaelin** [comment]
That's adorable! Idk if it'll kill the pokemon esthetic to change it to "a
wild type trait/phenotype" but I love it the way it is too!

**Comment by NoushinN** [comment]
![screen shot 2018-04-25 at 8 49 27 am](https://user-images.githubusercontent.com/37668936/39257146-ab3ff924-4865-11e8-81e1-8a848dcc045a.png)

Here's an attempt...any suggestions?

**Comment by NoushinN** [comment]
Here's an attempt...any suggestions?


![screen shot 2018-04-25 at 8 52 22 am](https://user-images.githubusercontent.com/37668936/39257273-00dc58dc-4866-11e8-9241-3d3f60d256c2.png)

**Comment by NoushinN** [comment]
This?

![screen shot 2018-04-25 at 9 01 07 am](https://user-images.githubusercontent.com/37668936/39257802-3dad5cb0-4867-11e8-9034-ba4e1a877189.png)

**Comment by NoushinN** [comment]
..
![screen shot 2018-04-25 at 9 04 53 am](https://user-images.githubusercontent.com/37668936/39258025-c70006b6-4867-11e8-9fe9-ce5e1a632c4b.png)

**Comment by ababaian** [comment]
That's a good first draft @NoushinN. It's great we're all helping out (and it's fun) but we need to have a laser focus on what we're doing.

We need to have a clear definition though of what art/style we're going to use for promotional materials. The Ramones / Rage Against logos are for sticker designs, they aren't for promotion.

If we're going with the 90s theme for promotion then we should stick to that. Also all materials should contain the main [hackseq logo](https://www.hackseq.com/s/hackseq_logotar.gz) and a piece of artwork. You can color-shift the main logo to fit the slide if that's necessary.

One idea: If we have a slide then using a photo showing people working together like [this](https://static1.squarespace.com/static/56e4a3eb01dbae3492a238b0/t/582ef3fdc534a5a764f37b81/1479675796528/?format=1500w) is a good idea. It emphasizes the social aspects of the activity.

Another idea: Put up the pokemon image as a main text and make a quick catchy tag for it to get people's attention like `"Do you have a project idea that keeps running away from you? Be a hackseq Team Leader and lead a team to catch it!"` Include application deadline / date of event and website.

The text info is good but should be shortened, maybe make the website  + twitter handle a separate line of it's own at the bottom so people find it quickly.

**Comment by NoushinN** [comment]
@ababaian great comments, you mean something like this?
![screen shot 2018-04-25 at 11 12 15 am](https://user-images.githubusercontent.com/37668936/39264375-956bdbd6-4879-11e8-8b4e-01cf9b155434.png)

**Comment by ababaian** [comment]
That's great, I wouldn't use that exact tag-line with that image, it's kind of a play on words with pokemon, but if you can make a 1-2 sentence tag which emphasizes working together as a team and socializing then that fits the photo.

Also `Hackseq` should be `hackseq` with forced lowercase.

**Comment by NoushinN** [comment]
oh! now catching the drift....how do you force lowercase? 
![screen shot 2018-04-25 at 11 25 46 am](https://user-images.githubusercontent.com/37668936/39265176-6f66b4cc-487b-11e8-9fea-20d72739ffb9.png)

**Comment by ababaian** [comment]
Nice! You can probably crop the `Hack SEQ` from the pokemon image to make it a bit bigger and that's a catchy poster ;)

Also I think that the pokemon image (with the top text removed) + that tagline would be a great tweet ; )

**Comment by NoushinN** [comment]
Cool! thanks for the live chat @ababaian 

![screen shot 2018-04-25 at 11 29 31 am](https://user-images.githubusercontent.com/37668936/39265392-ff6ac16c-487b-11e8-9bf1-ac5dd61cf9bd.png)

**Comment by NoushinN** [comment]
![slide4](https://user-images.githubusercontent.com/37668936/39265489-3caa38be-487c-11e8-8b2e-1b1f859f4ed5.jpg)

Here's the final image attached

**Comment by ababaian** [comment]
All final images at the highest resolution or raw formats should be deposited to the [`media folder`](https://github.com/hackseq/hackseq18/tree/master/media)

**Comment by bfjia** [comment]
Some sponsors are asking for some posters/material to distribute to advertise for hackseq18. Is there a specific one you guys want to use?

**Comment by ababaian** [comment]
The best thing we have is probably this guy:

![hackseq18_gb](https://user-images.githubusercontent.com/9220907/44932788-a80dd080-ad1b-11e8-9064-25d07806673a.png)


I can design a full poster (letter sized) this weekend and get it to you on Tuesday : ) +1

Edit: By Tuesday I totally meant Wednesday (busy weekend :/ )

**Comment by bfjia** [comment]
thx :)

**Comment by ababaian** [comment]
## hackseq18 Letter-poster
@imasianxd 

[PDF hackseq18 poster Link](https://github.com/hackseq/hackseq18/files/2350516/hackseq18_Poster.pdf)

![hackseq18_poster](https://user-images.githubusercontent.com/9220907/45061534-bfb9c180-b059-11e8-9baa-b0d009e4c752.jpg)

**Comment by ababaian** [comment]
# Sticker Designs

## Grateful Dead
![gratefuldead_600](https://user-images.githubusercontent.com/9220907/45335556-cef6ae80-b534-11e8-9ec2-64183a1169c0.png)

## Ramones
![ramones_600](https://user-images.githubusercontent.com/9220907/45335557-cef6ae80-b534-11e8-8531-6a61ed6ba3f4.png)

## System of a Down
![soad_600](https://user-images.githubusercontent.com/9220907/45336057-c010fb80-b536-11e8-9897-63ce90842ec1.png)

**Comment by NoushinN** [comment]
Really cool! loving them all, shall share on twitter 🥇 💯

**Comment by ababaian** [comment]
Maybe don't share these; leave them as a surprise for the stickers for participants

**Comment by NoushinN** [comment]
ok..exclusive to participants

**Comment by alexsweeten** [comment]
![nirvana_hackseq](https://user-images.githubusercontent.com/7028404/45590952-99b5dc00-b8f9-11e8-98d0-eeeb251895c4.jpg)

Quick Nirvana theme.

**Comment by ababaian** [comment]
Man you killed it with that one!

**Comment by ababaian** [comment]
@SweetiePi would you be able to send me the high/original resolution of the image so I can get some stickers printed?

**Comment by alexsweeten** [comment]
@ababaian Sure, I've added it to our media folder [here](https://github.com/hackseq/hackseq18/blob/master/media/nirvana_hackseq.jpg)
